### ISSUE TITLE
CythonでコンパイルしたcoreがNuitkaで扱えない問題？

### ISSUE THREAD

**Issue by aoirint** [aoirint/voicevox_engine#3]
Windowsで扱えてるのはなぜ?（リコンパイルしようとしなければよい?）

https://nuitka.net/#:~:text=Added%20ignore%20list

単にコマンドの問題?

本当にvoicevox_coreが読み込まれている?

```
Traceback (most recent call last):
  File "***/run.dist/run.py", line 334, in <module>
  File "***/run.dist/run.py", line 75, in make_synthesis_engine
AttributeError: module 'core' has no attribute 'initialize'
```

**Comment by aoirint** [comment]
https://github.com/aoirint/voicevox_engine/actions/runs/1232799139

```shell
import core
print(core)
```

```shell
$ ./run --voicevox_dir=$(pwd) --voicelib_dir=$(pwd)
Notice: --voicevox_dir is ***/run.dist
<module 'core' (<class 'nuitka_module_loader'>)>
Traceback (most recent call last):
  File "***/run.dist/run.py", line 335, in <module>
  File "***/run.dist/run.py", line 76, in make_synthesis_engine
AttributeError: module 'core' has no attribute 'initialize'
```

**Comment by aoirint** [comment]
やはりcpythonでsoになったモジュールを読み込めてない問題な気がする

**Comment by aoirint** [comment]
あ、そもそもVOICEVOX Core Python packageをpip installしてなかったわ
